In [ ]:
# Wrapper methods are a type of feature selection methods that involve using a predictive model(ML model) to score the combination of features.

# It create a subset of input feature from orginal feature than try ML algorithm and find r2/accuracy score. Based on r2 score it select best feature.

# They are called 'Wrapper' method because they 'wrap' this type of model based evaluation around the feature selection process.

# Step of wrapper method
    # 1. Subset Generation
    # 2. Subset Evaluation
    # 3. Stoping Criterion

In [ ]:
# Problems with too many features include:

# Overfitting

# High computational cost

# Lower model interpretability

# Noise affecting predictions

In [ ]:
# Type of Wrapper feature selection
    # Exhaustive feature selection
    # Forward selection
    # Backward elimination
    # Recursive feature elimination

In [ ]:
# Exhaustive feature selection/Best subset selection
    # Try out all the subset combination
    # Example:
    # f1,f2,y: try: f1-y, f2-y, f1,f2-y : find score and select best subset combination.

In [ ]:
# Disadvantages:
    # 1. Computational Complexity: Need 2^n-1 evaluation
    # 2. Risk of overfitting
    # 3. Require good evaluation metric

# Note: It is best for low number of feature dataset.
# It is better to use filter method than use wrapper method

In [2]:
# Code
from sklearn.linear_model import LogisticRegression, LinearRegression
from sklearn.model_selection import cross_val_score
import pandas as pd

In [3]:
# Import Dataset
df=pd.read_csv('iris.csv')
df.head(2)

   sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa

In [4]:
# Train the model with feature selection
from mlxtend.feature_selection import ExhaustiveFeatureSelector as EFS
lr=LogisticRegression()
sel=EFS(
    lr,
    max_features=3,
    scoring='accuracy',
    cv=5
)

In [5]:
# Fit the model
model = sel.fit(df.iloc[:,:4],df['variety'])

Features: 14/14

In [6]:
model.best_score_

np.float64(0.9666666666666668)

In [7]:
model.best_feature_names_

('sepal.length', 'petal.length', 'petal.width')

In [ ]:
# Sequential Backward Selection(SBS):
    # First train the model on whole dataset
    # Then Eliminate column one by one and train model
# Start → All Features → Remove one by one → Best subset
# This model is more faster
# Disadvantages:
# Can miss best feature
# Iteration will be the number of feature

In [ ]:
# Step-by-Step Process
# F={X1​,X2​,X3​,X4​,X5​}
# Train a model using all features.
# Remove X1......=F1 score
# Remove X2.......= f1 score
#.......

In [ ]:
# Sequential Forward Selection(SFS):
# Sequential Forward Selection starts with no features.
# Adds one feature at a time that improves the model performance the most.
# Start → No Features → Add one by one → Best subset

In [14]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from mlxtend.feature_selection import SequentialFeatureSelector as SFS
from sklearn.preprocessing import StandardScaler
import numpy as np

In [11]:
# Load Dataset
Data=pd.read_csv('BostonHousing.csv')
Data.sample(3)

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,b,lstat,medv
447,9.92485,0.0,18.10,0,0.740,6.251,96.6,2.1980,24,666,20.2,388.52,16.44,12.6
355,0.10659,80.0,1.91,0,0.413,5.936,19.5,10.5857,4,334,22.0,376.04,5.57,20.6
370,6.53876,0.0,18.10,1,0.631,7.016,97.5,1.2024,24,666,20.2,392.05,2.96,50.0

In [10]:
# separate the target variable
X = Data.drop("medv", axis=1)
y = Data['medv']

# split the data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

print(X_train.shape)

(404, 13)

In [13]:
# Perform StandardScalar
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [15]:
# Perform Linear regression model
model = LinearRegression()

print("training",np.mean(cross_val_score(model, X_train, y_train, cv=5, scoring='r2')))
print("testing",np.mean(cross_val_score(model, X_test, y_test, cv=5, scoring='r2')))

training 0.7025123301096213
testing 0.6514899901155404

In [ ]:
# Perform backward elimination

lr = LinearRegression()

# perform backward elimination
sfs = SFS(lr, k_features='best',
           forward=True, 
           floating=False, 
           scoring='r2',cv=5)

sfs.fit(X_train, y_train)

c:\Python3.13.1\Lib\site-packages\sklearn\externals\_numpydoc\docscrape.py:203: UserWarning: potentially wrong underline length...
Examples
----------- in
Sequential Feature Selection for Classification and Regression.
...
  while not self._is_at_section() and not self._doc.eof():

SequentialFeatureSelector(estimator=LinearRegression(), k_features=(1, 13),
                          scoring='r2')

In [18]:
# Show the best feature index
sfs.k_feature_idx_

(0, 1, 4, 5, 7, 8, 9, 10, 11, 12)

In [19]:
# Now perform linear regression
X_train_sel = sfs.transform(X_train)
X_test_sel = sfs.transform(X_test)

model = LinearRegression()

print("training",np.mean(cross_val_score(model, X_train_sel, y_train, cv=5, scoring='r2')))
print("testing",np.mean(cross_val_score(model, X_test_sel, y_test, cv=5, scoring='r2')))

training 0.7100327839218562
testing 0.7205819296124483

In [20]:
X_train_sel.shape

(404, 10)

In [ ]:
# Recursive Feature Elimination:
# RFE repeatedly builds a model and removes the weakest feature until only the most useful features remain.
# It works by recursively removing the least important features and building the model again until the optimal number of features remains.

In [ ]:
# Recursive elimination take two argument:
# 1. Algorithm
# 2. Feature
# Than base on algorithm it select best feature
# Feature selection vary algorithm to algorithm
# DT give weight, LR give coefficient and select feature

In [ ]:
# RFE follows a backward selection process.

# It starts with all features, then removes the least important feature step by step.

# Process
    # Train a model using all features.
    # Measure feature importance.
    # Remove the least important feature.
    # Train the model again with remaining features.
    # Repeat until desired number of features remains.
    # This is why it is called recursive (repeated process).

In [ ]:
# RFE helps to:

# Remove irrelevant features

# Improve model performance

# Reduce model complexity

In [ ]:
# If dataset has n features

# RFE performs:

# 1st iteration → n features
# 2nd iteration → n−1 features
# 3rd iteration → n−2 features
# Until k features remain.

In [ ]:
# Import Data set
Wine_data=pd.read_csv('wine_data.csv')

,1,14.23,1.71,2.43,15.6,127,2.8,3.06,.28,2.29,5.64,1.04,3.92,1065
0,1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
1,1,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
2,1,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480

In [ ]:
# Set column name
Wine_data.columns = ['Class label', 'Alcohol', 'Malic acid', 'Ash',
                   'Alcalinity of ash', 'Magnesium', 'Total phenols',
                   'Flavanoids', 'Nonflavanoid phenols', 'Proanthocyanins',
                   'Color intensity', 'Hue', 'OD280/OD315 of diluted wines',
                   'Proline']

In [26]:
# Show the data set
Wine_data.head(3)
print('Class labels', np.unique(Wine_data['Class label']))

Class labels [1 2 3]

In [29]:
# separate the target variable
X = Wine_data.drop('Class label', axis=1)
y = Wine_data['Class label']

# split the data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(
    X, y, 
    test_size=0.2, 
    random_state=1)

print(X_train.shape)

(141, 13)

In [30]:
# Perform StandarScalar
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train_std = sc.fit_transform(X_train)
X_test_std = sc.transform(X_test)

In [33]:

# Recursive Feature Selection
from sklearn.linear_model import LogisticRegression
from sklearn.feature_selection import RFE
lr = LogisticRegression(solver='lbfgs', random_state=123, max_iter=1000)
rfe = RFE(estimator=lr, n_features_to_select=5, step=1)
rfe.fit(X_train_std, y_train)
X_train_sub = rfe.transform(X_train_std)

In [35]:
# Which column selected
rfe.support_
Wine_data.columns[1:][rfe.support_]

Index(['Alcohol', 'Flavanoids', 'Color intensity', 'Hue', 'Proline'], dtype='object')

In [36]:
# RFE as Part of a Pipeline
from sklearn.model_selection import GridSearchCV
from sklearn.neighbors import KNeighborsClassifier
from sklearn.pipeline import make_pipeline
pipe = make_pipeline(RFE(estimator=lr, step=1),
                     KNeighborsClassifier())
parameters = {'rfe__n_features_to_select': range(1, 13), 
              'kneighborsclassifier__n_neighbors': range(1, 10) }

grid = GridSearchCV(pipe, param_grid=parameters, cv=10, n_jobs=-1)
grid.fit(X_train_std, y_train)

print('Best params:', grid.best_params_)
print('Best accuracy:', grid.best_score_)

Best params: {'kneighborsclassifier__n_neighbors': 1, 'rfe__n_features_to_select': 9}
Best accuracy: 0.9714285714285715

In [37]:
# Reduced feature set from grid search

grid.best_estimator_.score(X_test_std, y_test)

0.9444444444444444

In [38]:
# Full feature set for reference

knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train_std, y_train)
knn.score(X_test_std, y_test)

0.9444444444444444

In [ ]:
# Embedded:
# Embedded feature selection means the model selects important features automatically while training.
# It is called embedded because the selection of important features is built into (embedded in) the machine learning algorithm itself.
# Embedded method trains the model and selects important features at the same time.
# Embedded methods are used in models such as:
    # Lasso Regression
    # Ridge Regression
    # Elastic Net
    # Decision Tree
    # Random Forest
    # Gradient Boosting

In [ ]:
# Step-by-step process

# Model starts training with all features
# Model evaluates contribution of each feature
# Less important features get low weight or zero weight
# Important features get higher weight
# Final model keeps only the useful features