In [ ]:
            #-----Feature Scaling-------#
# Feature scaling is a technique  to standardize the independent features present in the data in a fixed range.
# Bring all input independent features to a similar numerical range or scale.
# Prevent dominance of large-Scale feature.
# This is the last step among all feature engineering process.

In [ ]:
# Why do we need Feature Enigineering?
    # Ensures fair contribution of features
    # Required for distance-based methods
    # Improves model convergence 
    # Without scaling ML algorithms do not perform well

In [ ]:
# Types of Scaling:
    # 1. Standardization
    # 2. Normalization

In [ ]:
# Standardization: Also called as Z score normalization.
# Formula of Standardization: Xi-Mean/Standard Deviation 
# After scaling mean of scaled data will be 0
# After scaling SD of scaled data will be 1

# Standard deviation: measures the spread or dispersion of a dataset relative to its mean.
    # Low standard deviation → data points are close to the mean
    # High standard deviation → data points are widely spread out

In [1]:
            # -------Standardization Example-------#
# Import required libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [7]:
# Import Dataset
Data=pd.read_csv('Social_Network_Ads.csv')
Data.shape

(400, 5)

In [8]:
# Check the dataset
Data.head()

    User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [9]:
# Drop first two column
Data=Data.iloc[:,2:]

In [10]:
# Again Check the data
Data.head()

   Age  EstimatedSalary  Purchased
0   19            19000          0
1   35            20000          0
2   26            43000          0
3   27            57000          0
4   19            76000          0

In [14]:
# It is recommended that before scaling, devide the dataset into train test split.
    # Train test split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(
    Data.drop('Purchased', axis=1),
    Data['Purchased'],
    test_size=0.3,
    random_state=0
    )

In [15]:
# Shape of X_train
X_train.shape

(280, 2)

In [16]:
# Shape of X_test
X_test.shape

(120, 2)

In [24]:
# Now perform standardization
from sklearn.preprocessing import StandardScaler

# Create object of StandarScaler class
scaler=StandardScaler()

# fit the scaler to the train set, it will leran the parameters(mean, SD)
# perform fit only with train set not test_set, it prevent data leakage

scaler.fit(X_train)
# Transform train and test set
X_train_scaled=scaler.transform(X_train)
X_test_scaled=scaler.transform(X_test)

In [ ]:
# type of X_train, X_test
type(X_train_scaled)  # X_train_scaled loses column names
type(X_test_scaled)  # X_test_scaled loses column names

numpy.ndarray

In [35]:
# Convert the numpy array to pandas dataframe
X_train_scaled=pd.DataFrame(X_train_scaled, columns=X_train.columns)
X_test_scaled=pd.DataFrame(X_test_scaled, columns=X_test.columns)

In [ ]:
# Check X_train_scaled and X_test_scaled
X_train_scaled
X_test_scaled

          Age  EstimatedSalary
0   -0.771013         0.497201
1    0.013305        -0.572804
2   -0.280814         0.150172
3   -0.771013         0.265849
4   -0.280814        -0.572804
..        ...              ...
115  1.091743        -0.139018
116  0.699584         1.769639
117 -0.672973         0.555039
118  0.797624         0.352606
119  0.895664        -0.543885

[120 rows x 2 columns]

In [38]:
# Compare original X_train and Scaled X_train
np.round(X_train.describe(), 1)     # Age and salary in different scale

         Age  EstimatedSalary
count  280.0            280.0
mean    37.9          69807.1
std     10.2          34641.2
min     18.0          15000.0
25%     30.0          43000.0
50%     37.0          70500.0
75%     46.0          88000.0
max     60.0         150000.0

In [41]:
np.round(X_train_scaled.describe(), 1)   # Age and Salary in same scale

         Age  EstimatedSalary
count  280.0            280.0
mean     0.0              0.0
std      1.0              1.0
min     -1.9             -1.6
25%     -0.8             -0.8
50%     -0.1              0.0
75%      0.8              0.5
max      2.2              2.3